---
title: "cluster_difference_in_means_estimator"
author: "yangsong"
date: "12/28/2019"
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    theme: united
    toc: yes
  pdf_document:
    toc: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Dataset
```{r}
set.seed(88)
# Number of clusters
M <- 100
# Number of clusters randomly assigned to the control cohort
mc <- 95
# Number of clusters randomly assigned to the treatment cohort
mt <- 5
# Number of samples in each cluster
average_samples_in_each_cluster <- 100
samples_per_cluster <- sample(10:1000, M, replace=FALSE)
# We intentionally make cluster's mean to be correlated with the number of samples in the clusters
mean_per_cluster <- rnorm(M, mean=100+samples_per_cluster * 0.1, sd=10)

individual_samples <-
  lapply(1:M, 
         function(x) rnorm(n=samples_per_cluster[x], mean = mean_per_cluster[x], sd=3))

sim <- 10000

```



# Difference in Means Estimator
```{r}
set.seed(8)
yt_yc_diff <- c()
for(i in 1:sim){
     control_cohort <- sample(1:M, mc, replace=FALSE)
     treatment_cohort <- sample(1:M, mt, replace=FALSE)
     control_cohort_mean <- mean(unlist(individual_samples[control_cohort]))
     treatment_cohort_mean <- mean(unlist(individual_samples[treatment_cohort]))
     yt_yc_diff <- c(yt_yc_diff, treatment_cohort_mean - control_cohort_mean)
}
 
mean(yt_yc_diff)
```


# Horvitz-Thompson Estimator
```{r}
set.seed(8)
yt_yc_diff <- c()
for(i in 1:sim){
  control_cohort <- sample(1:M, mc, replace=FALSE)
  treatment_cohort <- sample(1:M, mt, replace=FALSE)
  control_cohort_mean <- sum(unlist(individual_samples[control_cohort])) / mc
  treatment_cohort_mean <- sum(unlist(individual_samples[treatment_cohort])) / mt
  yt_yc_diff <- c(yt_yc_diff, (treatment_cohort_mean - control_cohort_mean) * M / sum(samples_per_cluster))
}

mean(yt_yc_diff)
```








