---
title: "A simulation on the diff-in-diff method"
author: "yangsong"
date: "10/31/2019"
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    theme: united
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# One group, pre-post test
## Type one error / False Positive Test
```{r, message=FALSE, warning=FALSE}
# No effects in post period.  We assume there are two cohorts - pre and post and we want to check the significance of mean differences between two cohorts
# Without correcting for covariance of pre-post data points of each sample (Wrong way)
sig_sim <- 0 
sim <- 10000
samples_per_cohort <- 5000

set.seed(888)
for (i in 1:sim){
  pre <- rpois(samples_per_cohort, 10)
  post <- pre + rnorm(samples_per_cohort, mean=0, sd=1)
  pre_post_mean <- mean(post) - mean(pre)
  pre_sample_var <-  var(pre) * length(pre) / (length(pre) - 1)
  post_sample_var <-  var(post) * length(post) / (length(post) - 1)

  # pre post samples are no longer independent to each other, need to account for the covariance term
  pre_post_se <- sqrt(pre_sample_var / length(pre) + post_sample_var / length(post))
  
  z_score <- pre_post_mean / pre_post_se
  if((z_score >= 1.96) | (z_score <= -1.96)){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Type one error is: ", sig_sim / sim))


# Correct for covariance of pre-post data points of each sample (Correct way)
sig_sim <- 0 
set.seed(888)
for (i in 1:sim){
  pre <- rpois(samples_per_cohort, 10)
  post <- pre + rnorm(samples_per_cohort, mean=0, sd=1)
  pre_post_mean <- mean(post) - mean(pre)
  pre_sample_var <-  var(pre) * length(pre) / (length(pre) - 1)
  post_sample_var <-  var(post) * length(post) / (length(post) - 1)

  # pre post samples are no longer independent to each other, need to account for the covariance term
  pre_post_se <- sqrt(pre_sample_var / length(pre) + post_sample_var / length(post) - 2 * cov(pre, post) / length(pre))
  
  z_score <- pre_post_mean / pre_post_se
  if((z_score >= 1.96) | (z_score <= -1.96)){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Type one error is: ", sig_sim / sim))


# Linear regression (Linear regression assumes each samples are independent to each other, so I think the result should be similar to the one without correcting for the pre-post covariance)  (Wrong way)
sig_sim <- 0 
set.seed(888)
for (i in 1:sim){
  pre <- rpois(samples_per_cohort, 10)
  post <- pre + rnorm(samples_per_cohort, mean=0, sd=1)
  # our treatment covariates
  cohorts <- c(rep(0, samples_per_cohort), rep(1, samples_per_cohort))
  Y <- c(pre, post)
  linear_model <- lm(Y ~ cohorts)
  # Extract the p value associated with the cohorts (pre-post)
  if (summary(linear_model)$coefficients[2,4] <= 0.05){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Type one error is: ", sig_sim / sim))



# Take diff first, and then check for the differences distribution 
sig_sim <- 0 
set.seed(888)
for (i in 1:sim){
  pre <- rpois(samples_per_cohort, 10)
  post <- pre + rnorm(samples_per_cohort, mean=0, sd=1)
  pre_post_diff_mean <- mean(post - pre)
  pre_post_diff_var <- var(post -pre) * length(post - pre) / (length(post - pre) - 1)
  # pre post samples are no longer independent to each other, need to account for the covariance term
  pre_post_diff_se <- sqrt(pre_post_diff_var / length(post - pre))
  z_score <- pre_post_diff_mean / pre_post_diff_se
  if((z_score >= 1.96) | (z_score <= -1.96)){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Type one error is: ", sig_sim / sim))


```



## Power Test
```{r, message=FALSE, warning=FALSE}
# The value increases by 1 in the post period.  We assume there are two cohorts - pre and post and we want to check the significance of mean differences between two cohorts
# Without correcting for covariance of pre-post data points of each sample (Wrong way)
sig_sim <- 0 
sim <- 10000
samples_per_cohort <- 5000
set.seed(888)
for (i in 1:sim){
  pre <- rpois(samples_per_cohort, 10)
  post <- pre + rnorm(samples_per_cohort, mean=0.08, sd=1)
  pre_post_mean <- mean(post) - mean(pre)
  pre_sample_var <-  var(pre) * length(pre) / (length(pre) - 1)
  post_sample_var <-  var(post) * length(post) / (length(post) - 1)

  # pre post samples are no longer independent to each other, need to account for the covariance term
  pre_post_se <- sqrt(pre_sample_var / length(pre) + post_sample_var / length(post))
  
  z_score <- pre_post_mean / pre_post_se
  if((z_score >= 1.96) | (z_score <= -1.96)){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Power is: ", sig_sim / sim))


# Correct for covariance of pre-post data points of each sample (Correct way)
sig_sim <- 0 
set.seed(888)
for (i in 1:sim){
  pre <- rpois(samples_per_cohort, 10)
  post <- pre + rnorm(samples_per_cohort, mean=0.08, sd=1)
  pre_post_mean <- mean(post) - mean(pre)
  pre_sample_var <-  var(pre) * length(pre) / (length(pre) - 1)
  post_sample_var <-  var(post) * length(post) / (length(post) - 1)

  # pre post samples are no longer independent to each other, need to account for the covariance term
  pre_post_se <- sqrt(pre_sample_var / length(pre) + post_sample_var / length(post) - 2 * cov(pre, post) / length(pre))
  
  z_score <- pre_post_mean / pre_post_se
  if((z_score >= 1.96) | (z_score <= -1.96)){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Power is: ", sig_sim / sim))


# Linear regression (Linear regression assumes each samples are independent to each other, so I think the result should be similar to the one without correcting for the pre-post covariance) (Wrong way)
sig_sim <- 0  
set.seed(888)
for (i in 1:sim){
  pre <- rpois(samples_per_cohort, 10)
  post <- pre + rnorm(samples_per_cohort, mean=0.08, sd=1)
  # our treatment covariates
  cohorts <- c(rep(0, samples_per_cohort), rep(1, samples_per_cohort))
  Y <- c(pre, post)
  linear_model <- lm(Y ~ cohorts)
  # Extract the p value associated with the cohorts (pre-post)s
  if (summary(linear_model)$coefficients[2,4] <= 0.05){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Power is: ", sig_sim / sim))


# Take diff first, and then check for the differences distribution 
sig_sim <- 0 
set.seed(888)
for (i in 1:sim){
  pre <- rpois(samples_per_cohort, 10)
  post <- pre + rnorm(samples_per_cohort, mean=0.08, sd=1)
  pre_post_diff_mean <- mean(post - pre)
  pre_post_diff_var <- var(post -pre) * length(post - pre) / (length(post - pre) - 1)
  # pre post samples are no longer independent to each other, need to account for the covariance term
  pre_post_diff_se <- sqrt(pre_post_diff_var / length(post - pre))
  z_score <- pre_post_diff_mean / pre_post_diff_se
  if((z_score >= 1.96) | (z_score <= -1.96)){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Power is: ", sig_sim / sim))


```

In summary, if we don't account for the data points covariance between each samples, then we will underestimate the type one error, as well as underestimate the power of the test




# Two groups, pre-post test
## Type one error / False Positive Test
```{r, message=FALSE, warning=FALSE}
# When there is no treatment effect
# Without correcting for covariance of pre-post data points of each sample (Wrong way)
sig_sim <- 0 
sim <- 10000
samples_per_cohort <- 5000

seasonal_effects <- 3
treatment_effects <- 0

control_mean <- 10
treatment_mean <- 15


set.seed(888)
for (i in 1:sim){
  pre_control <- rpois(samples_per_cohort, control_mean)
  post_control <- pre_control + rnorm(samples_per_cohort, mean=seasonal_effects, sd=1)
  pre_post_control_mean <- mean(post_control) - mean(pre_control)
  pre_control_var <-  var(pre_control) * length(pre_control) / (length(pre_control) - 1)
  post_control_var <-  var(post_control) * length(post_control) / (length(post_control) - 1)

  pre_treatment <- rpois(samples_per_cohort, treatment_mean)
  post_treatment  <- pre_treatment + rnorm(samples_per_cohort, mean=seasonal_effects+treatment_effects, sd=1)
  
  pre_post_treatment_mean <- mean(post_treatment) - mean(pre_treatment)
  pre_treatment_var <-  var(pre_treatment) * length(pre_treatment) / (length(pre_treatment) - 1)
  post_treatment_var <-  var(post_treatment) * length(post_treatment) / (length(post_treatment) - 1)
  
  # pre post samples are no longer independent to each other, need to account for the covariance term
  pre_post_control_var <- pre_control_var / length(pre_control) + post_control_var / length(post_control)
  pre_post_treatment_var <- pre_treatment_var / length(pre_treatment) + post_treatment_var / length(post_treatment)
  
  diff_diff_se <- sqrt(pre_post_control_var + pre_post_treatment_var)
  
  z_score <- (pre_post_treatment_mean -  pre_post_control_mean ) / diff_diff_se
  if((z_score >= 1.96) | (z_score <= -1.96)){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Type one error is: ", sig_sim / sim))





# Correct for covariance of pre-post data points of each sample (Correct way)
sig_sim <- 0 
set.seed(888)
for (i in 1:sim){
  pre_control <- rpois(samples_per_cohort, control_mean)
  post_control <- pre_control + rnorm(samples_per_cohort, mean=seasonal_effects, sd=1)
  pre_post_control_mean <- mean(post_control) - mean(pre_control)
  pre_control_var <-  var(pre_control) * length(pre_control) / (length(pre_control) - 1)
  post_control_var <-  var(post_control) * length(post_control) / (length(post_control) - 1)

  pre_treatment <- rpois(samples_per_cohort, treatment_mean)
  post_treatment  <- pre_treatment + rnorm(samples_per_cohort, mean=seasonal_effects+treatment_effects, sd=1)
  
  pre_post_treatment_mean <- mean(post_treatment) - mean(pre_treatment)
  pre_treatment_var <-  var(pre_treatment) * length(pre_treatment) / (length(pre_treatment) - 1)
  post_treatment_var <-  var(post_treatment) * length(post_treatment) / (length(post_treatment) - 1)
  
  # pre post samples are no longer independent to each other, need to account for the covariance term
  pre_post_control_var <- pre_control_var / length(pre_control) + post_control_var / length(post_control) - 2 * cov(pre_control, post_control) / length(pre_control)
  
  pre_post_treatment_var <- pre_treatment_var / length(pre_treatment) + post_treatment_var / length(post_treatment) - 2 * cov(pre_treatment, post_treatment) / length(pre_treatment)
  
  diff_diff_se <- sqrt(pre_post_control_var + pre_post_treatment_var)
  
  z_score <- (pre_post_treatment_mean -  pre_post_control_mean ) / diff_diff_se
  if((z_score >= 1.96) | (z_score <= -1.96)){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Type one error is: ", sig_sim / sim))


# Linear regression
sig_sim <- 0 
set.seed(888)

for (i in 1:sim){
  pre_control <- rpois(samples_per_cohort, control_mean)
  post_control <- pre_control + rnorm(samples_per_cohort, mean=seasonal_effects, sd=1)
  
  pre_treatment <- rpois(samples_per_cohort, treatment_mean)
  post_treatment  <- pre_treatment + rnorm(samples_per_cohort, mean=seasonal_effects+treatment_effects, sd=1)

  Y = c(pre_control, pre_treatment, post_control, post_treatment)
  
  time = c(rep(0, length(pre_control) + length(pre_treatment)), rep(1, length(post_control) + length(post_treatment)))
  
  cohort = c(rep(0, length(pre_control)), rep(1, length(pre_treatment)), rep(0, length(post_control)), rep(1, length(post_treatment)))

  linear_model <- lm(Y ~ time*cohort)  

  if (summary(linear_model)$coefficients[4,4] <= 0.05){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Type one error is: ", sig_sim / sim))

```


## Power Test
```{r, message=FALSE, warning=FALSE}
sig_sim <- 0 
sim <- 10000
samples_per_cohort <- 5000

# the seasonal_effects won't affect our test result
seasonal_effects <- 3
treatment_effects <- 0.2

control_mean <- 10
treatment_mean <- 15

set.seed(888)
for (i in 1:sim){
  pre_control <- rpois(samples_per_cohort, control_mean)
  post_control <- pre_control + rnorm(samples_per_cohort, mean=seasonal_effects, sd=1)
  pre_post_control_mean <- mean(post_control) - mean(pre_control)
  pre_control_var <-  var(pre_control) * length(pre_control) / (length(pre_control) - 1)
  post_control_var <-  var(post_control) * length(post_control) / (length(post_control) - 1)

  pre_treatment <- rpois(samples_per_cohort, treatment_mean)
  post_treatment  <- pre_treatment + rnorm(samples_per_cohort, mean=seasonal_effects + treatment_effects, sd=1)
  
  pre_post_treatment_mean <- mean(post_treatment) - mean(pre_treatment)
  pre_treatment_var <-  var(pre_treatment) * length(pre_treatment) / (length(pre_treatment) - 1)
  post_treatment_var <-  var(post_treatment) * length(post_treatment) / (length(post_treatment) - 1)
  
  # pre post samples are no longer independent to each other, need to account for the covariance term
  pre_post_control_var <- pre_control_var / length(pre_control) + post_control_var / length(post_control)
  pre_post_treatment_var <- pre_treatment_var / length(pre_treatment) + post_treatment_var / length(post_treatment)
  
  diff_diff_se <- sqrt(pre_post_control_var + pre_post_treatment_var)
  
  z_score <- (pre_post_treatment_mean -  pre_post_control_mean ) / diff_diff_se
  if((z_score >= 1.96) | (z_score <= -1.96)){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Power is: ", sig_sim / sim))





# Correct for covariance of pre-post data points of each sample (Correct way)
sig_sim <- 0 
set.seed(888)
for (i in 1:sim){
  pre_control <- rpois(samples_per_cohort, control_mean)
  post_control <- pre_control + rnorm(samples_per_cohort, mean=seasonal_effects, sd=1)
  pre_post_control_mean <- mean(post_control) - mean(pre_control)
  pre_control_var <-  var(pre_control) * length(pre_control) / (length(pre_control) - 1)
  post_control_var <-  var(post_control) * length(post_control) / (length(post_control) - 1)

  pre_treatment <- rpois(samples_per_cohort, treatment_mean)
  post_treatment  <- pre_treatment + rnorm(samples_per_cohort, mean=seasonal_effects+treatment_effects, sd=1)
  
  pre_post_treatment_mean <- mean(post_treatment) - mean(pre_treatment)
  pre_treatment_var <-  var(pre_treatment) * length(pre_treatment) / (length(pre_treatment) - 1)
  post_treatment_var <-  var(post_treatment) * length(post_treatment) / (length(post_treatment) - 1)
  
  # pre post samples are no longer independent to each other, need to account for the covariance term
  pre_post_control_var <- pre_control_var / length(pre_control) + post_control_var / length(post_control) - 2 * cov(pre_control, post_control) / length(pre_control)
  
  pre_post_treatment_var <- pre_treatment_var / length(pre_treatment) + post_treatment_var / length(post_treatment) - 2 * cov(pre_treatment, post_treatment) / length(pre_treatment)
  
  diff_diff_se <- sqrt(pre_post_control_var + pre_post_treatment_var)
  
  z_score <- (pre_post_treatment_mean -  pre_post_control_mean ) / diff_diff_se
  if((z_score >= 1.96) | (z_score <= -1.96)){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Power is: ", sig_sim / sim))




# Linear regression
sig_sim <- 0 
set.seed(888)

for (i in 1:sim){
  pre_control <- rpois(samples_per_cohort, control_mean)
  post_control <- pre_control + rnorm(samples_per_cohort, mean=seasonal_effects, sd=1)
  
  pre_treatment <- rpois(samples_per_cohort, treatment_mean)
  post_treatment  <- pre_treatment + rnorm(samples_per_cohort, mean=seasonal_effects+treatment_effects, sd=1)

  Y = c(pre_control, pre_treatment, post_control, post_treatment)
  
  time = c(rep(0, length(pre_control) + length(pre_treatment)), rep(1, length(post_control) + length(post_treatment)))
  
  cohort = c(rep(0, length(pre_control)), rep(1, length(pre_treatment)), rep(0, length(post_control)), rep(1, length(post_treatment)))

  linear_model <- lm(Y ~ time*cohort)  

  if (summary(linear_model)$coefficients[4,4] <= 0.05){
    sig_sim <-  sig_sim + 1
  }
}
print(paste0("Power is: ", sig_sim / sim))


```

