---
title: "GEE_Model_Simulation"
author: "yangsong"
date: "11/17/2019"
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    theme: united
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Two groups, pre-post test
## Type one error / False Positive Test
```{r, message=FALSE, warning=FALSE}
library("gee")
# When there is no treatment effect
# We run a GEE model
sig_sim <- 0 
sim <- 1000
samples_per_cohort <- 5000

seasonal_effects <- 3
treatment_effects <- 0

control_mean <- 10
treatment_mean <- 15

for (i in 1:sim) {
  pre_control <- rpois(samples_per_cohort, control_mean)
  post_control <-
    pre_control + rnorm(samples_per_cohort, mean = seasonal_effects, sd = 1)

  pre_treatment <- rpois(samples_per_cohort, treatment_mean)
  post_treatment  <-
    pre_treatment + rnorm(samples_per_cohort,
    mean = seasonal_effects + treatment_effects,
    sd = 1)

  Y = c(pre_control, pre_treatment, post_control, post_treatment)

  time = c(rep(0, length(pre_control) + length(pre_treatment)), rep(1, length(post_control) + length(post_treatment)))

  cohort = c(rep(0, length(pre_control)),
             rep(1, length(pre_treatment)),
             rep(0, length(post_control)),
             rep(1, length(post_treatment)))
  subject = c(seq(1:length(pre_control)), 
              seq(length(pre_control)+1, length(pre_control)+length(pre_treatment)),
              seq(1:length(pre_control)),
              seq(length(pre_control)+1, length(pre_control)+length(pre_treatment)))
  
  gee_model <- gee(Y ~ cohort * time,
                id = subject, 
                family = gaussian,
                corstr = "independence")
   # Use the robust z score
   if (abs(summary(gee_model)$coefficients[4, 5]) >= 1.96) {
      sig_sim <-  sig_sim + 1
   }
}

print(sig_sim / sim)

```


## Power
```{r, message=FALSE, warning=FALSE}
library("gee")
# When there is no treatment effect
# We run a GEE model
sig_sim <- 0 
sim <- 1000
samples_per_cohort <- 5000

seasonal_effects <- 3
treatment_effects <- 0.2

control_mean <- 10
treatment_mean <- 15

for (i in 1:sim) {
  pre_control <- rpois(samples_per_cohort, control_mean)
  post_control <-
    pre_control + rnorm(samples_per_cohort, mean = seasonal_effects, sd = 1)

  pre_treatment <- rpois(samples_per_cohort, treatment_mean)
  post_treatment  <-
    pre_treatment + rnorm(samples_per_cohort,
    mean = seasonal_effects + treatment_effects,
    sd = 1)

  Y = c(pre_control, pre_treatment, post_control, post_treatment)

  time = c(rep(0, length(pre_control) + length(pre_treatment)), rep(1, length(post_control) + length(post_treatment)))

  cohort = c(rep(0, length(pre_control)),
             rep(1, length(pre_treatment)),
             rep(0, length(post_control)),
             rep(1, length(post_treatment)))
  subject = c(seq(1:length(pre_control)), 
              seq(length(pre_control)+1, length(pre_control)+length(pre_treatment)),
              seq(1:length(pre_control)),
              seq(length(pre_control)+1, length(pre_control)+length(pre_treatment)))
  
  gee_model <- gee(Y ~ cohort * time,
                id = subject, 
                family = gaussian,
                corstr = "independence")
   # Use the robust z score
   if (abs(summary(gee_model)$coefficients[4, 5]) >= 1.96) {
      sig_sim <-  sig_sim + 1
   }
}

print(sig_sim / sim)

```
